README.md

Previously the example code would cause an error due to `snap` (undefined) being referenced instead of `snapshot`.
Considered changing it away from 'const' since it's likely there'll be someone (like me) that wants to interact with _other_ snapshots while playing around with examples 😄

Update README.md: browser example code typo fixed

---

README.md
index.d.ts
src/ts/query.ts

Fixes missing types that prevent building `acebase` when `acebase-core` dependency has no `src` directory (npm/yarn distributions)
Needs new version of `acebase-core` to be published first

Fix: missing types

---

.npmignore

Temporarily allow sources and source maps to be included in npm distributions, fixes missing types

fix: include sources & maps in npm distribution

---

src/storage/binary/index.ts
src/test/keys.spec.ts

Adds a pre-check to prevent empty `''` keys to be used in `update` and `set` objects. This has already been fixed in `acebase-core` by https://github.com/appy-one/acebase-core/pull/24, added here to keep checks the same. Another option would be to to remove the key checks here and completely delegate it to `acebase-core`'s `PathInfo` class. This should be considered.
Also adds unit tests

Empty keys pre-check

---

.eslintrc.json

Do not allow single block statements without `{ }`

Add eslint `curly` rule

---

package-lock.json
package.json
src/api-local.ts
src/query.ts
src/test/query.spec.ts

Allows queries to be executed on non-indexed paths with $variables if values for those variables are passed as a filter.
Example:
```js
const messageCount = await db.query('users/$username/messages').filter('$username', 'in', ['user1', 'user2']).count();
```
Above essentially performs 2 queries (for user1 and user2) and combines the results

Allow wildcard path queries with given filter values

---

src/ipc/service/index.ts
src/ipc/service/shared.ts
src/ipc/service/start.ts
src/ipc/socket.ts
src/storage/binary/index.ts
src/storage/index.ts
src/test/tempdb.ts

This approach automatically starts a service ("daemon") for the target database in a separate process. The service will take on the master/primary role, all connecting clients will take on the worker role. This mode should become the default in the near future, as it eliminates the need to manually setup local master/worker clustering settings. It will also enable one to simultaneously use a single database file from different apps, which would previously require setting up an AceBaseServer!

New feature: socket IPC service

---

src/ipc/browser.ts
src/ipc/index.ts
src/ipc/socket.ts
src/storage/index.ts

The new Socket IPC mode added in v1.28.0 (#213) broke the browser build because NodeJS components were being accessed in the browser context. This PR fixes #215

Fix socket IPC breaking browser build #215

---

create-package-files

Fixes using AceBase from TypeScript ES modules (`"type": "module"` in _package.json_) and `"moduleResolution": "node16"` or `"moduleResolution": "nodenext"` in _tsconfig.json_
This adds `/index.d.ts` to the `export * from "../types"` statement in the generated _/dist/esm/index.d.ts_
Closes #203 and #219

Fixes #203 / #219

---

create-package-files
tsconfig.json

See #203 and #219
TODO: use updated acebase-core (see https://github.com/appy-one/acebase-core/pull/40)

fix tsc node16 module resolution

---

package-lock.json
package.json
src/data-index/data-index.ts
src/data-index/geo-index.ts
src/node-info.ts
src/node-value-types.ts
src/storage/binary/index.ts
src/storage/custom/index.ts
src/storage/custom/local-storage/transaction.ts
src/storage/mssql/index.ts
src/storage/sqlite/index.ts
tsconfig.json

When using AceBase in an external project using `"skipLibraryCheck": false` (default) in its _tsconfig.json_, it will yield compile errors that are not shown when compiling AceBase itself with `tsc`. Why there are no TypeScript errors should be investigated further. See #220

Fix (invisible) tsc compile errors

---

README.md
package-lock.json
package.json
src/ipc/index.ts
src/ipc/service/index.ts
src/ipc/service/shared.ts
src/ipc/service/start.ts
src/ipc/socket.ts
src/test/bulk-import.spec.ts

This fixes a process not being able to exit because the socket IPC was keeping references to `stdout` and `stderr`. It also adds some command level settings and documentation!

Fix: Socket IPC preventing process exit

---

package-lock.json
package.json
src/api-local.ts
src/storage/index.ts
src/test/schema.spec.ts

This enables one to introduce schema definitions to an existing database, but logs warnings instead of denying writes not conforming to the schema.

Feature: "warn only" schema definitions

---

src/storage/index.ts
src/test/events.spec.ts

If `mutations` or `notify_mutations` are set on a path containing wildcards (* or named variables), the mutation's `target` is not being set correctly.
Example:
```js
db.ref('users/*/books').on('mutations', (mutations) => {
mutations.forEach(snap => {
const m = snap.val();
const target = m.target;
// if mutation is on `users/user1/books/book1/title`, target contains ['ooks', 'book1', 'title']
// but target should be ['book1', 'title']
});
});
```
TODO: `snap.ref.path` probably contains `users/*/books`, but should be `users/user1/books` in above example. Check this, fix it if true.

Fix `target` of `mutations` events on wildcard paths

---

src/ipc/browser.ts

Old Safari versions (up to iOS 15?) don't support BroadcastChannel, and when AceBase is runs in a webworker there is no localStorage to fallback to: disable browser IPC in this case.

Add support for old Safari in webworker

---

src/btree/binary-tree.ts
src/storage/binary/test.spec.ts

This fixes the issue described in #239, where adding children to an empty tree causes issues because the binary tree leaf was left behind empty. This code changes the delete behaviour to rebuild the tree after a leaf has become empty and its parent node will be left without child entries

Fix issue #239

---

src/btree/binary-tree.ts
src/storage/binary/test.spec.ts

This causes single-leaf trees to be saved when they reach their max number of entries, so they can be rebuilt (increased in size) when a next batch of add operations is processed.

Fix issue #242

---

src/btree/binary-tree.ts
src/storage/binary/index.ts

Dramatically increase the performance of (re)wiring large nodes spanning multiple allocation ranges (logical pages) by:
* Growing the max number of node entries faster (+50% instead of +10% per rebuild)
* Optimizing the code that requests individual record entries for allocated ranges

Drastically improve large node (re)writes

---

src/btree/binary-tree-leaf-entry.ts
src/btree/binary-tree.ts
src/data-index/data-index.ts
src/test/tempdb.ts

This fixes memory issues when building a large index. Looping the leaf values is now done without recursion to prevent memory heaping up in the callstack

Fix large index builds

---

README.md

there may be more typos in the readme but I fixed what I spotted

fix parentheses in code snipets
